chore(sleep): add more info to sleep bluetooth command

diff --git a/sleep b/sleep
--- a/sleep
+++ b/sleep
@@ -7,5 +7,5 @@ BLUEUTIL_PATH=$(brew --prefix)/bin/blueutil
 BT_DEVICE_ID="70-26-05-3b-ba-2c"
 
 if [ $($BLUEUTIL_PATH --is-connected $BT_DEVICE_ID) == 1 ]; then
-  $BLUEUTIL_PATH --disconnect $BT_DEVICE_ID || echo "Device not found..."
+  $BLUEUTIL_PATH --disconnect $BT_DEVICE_ID --info $BT_DEVICE_ID || echo "Device not found..."
 fi
